
#런타임에러 
#select count(*) as count 
#from ECOLIT_DATA 
#WHERE GENOTYPE &2=0
#    AND(GENOTYPE &1 >0 OR GENOTYPE &4>0); 


SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2) = 0
  AND ((GENOTYPE & 1) > 0 OR (GENOTYPE & 4) > 0);
